_config.yml
title: "The Synthetic Summit 2025 Catalogue"
description: "An interactive catalogue featuring essays and videos on AI governance and speculative art."
markdown: kramdown
theme: minima  # You can choose another supported theme